- perf-event-open-sys/Cargo.toml
- perf-event-open-sys/regenerate.sh
- perf-event-open-sys/src/bindings_aarch64.rs
- perf-event-open-sys/src/bindings_x86_64.rs
As it turns out, it is only really needed for a few key structs. In addition, having these extra structs be #[non_exhaustive] is rather inconvenient.
> Remove the `#[non_exhaustive]` attribute on most structs

- Cargo.toml
- perf-event/Cargo.toml
- perf-event/src/builder.rs
- perf-event/src/flags.rs
- perf-event/src/group_data.rs
- perf-event/src/lib.rs
- perf-event/src/sampler.rs
As in the title, this PR uses the `perf_event_data` crate to add support for parsing `Record`s gotten from a sampler. I've also replaced the implementation details of the various counter read related structs with types from `perf_event_data`.
The detailed changes here are
- `perf_event_data` is now reexported as the `data` module in the crate root. I have used `#[doc(inline)]` so that the docs are inlined into the main crate.
- The internals of `GroupData`, `GroupEntry`, `GroupIter`, and `CounterData` have all been replaced with types from `perf_event_data`. No public API changes have been made here.
- `Counter` now keeps a `ParseConfig` from `perf_event_data` internally instead of just a `ReadFormat` value. This can now be accessed via `Counter::config`. This increases the size of …
> Add support for parsing `Record`s via the `perf_event_data` crate

- perf-event/src/events.rs
This commit adds two new event types to events::Software:
- BPF_OUTPUT
- CGROUP_SWITCHES
Neither of these two enum values happen to be documented in the perf_event_open(2) manpage. The BPF_OUTPUT variant is mentioned in the bpf-helpers(7) manpage so I've made the documentation point there. For CGROUP_SWITCHES I have just taken a guess since between the manpage and perf_event.h header there is _no documentation whatsoever_.
> Add missing software events to `events::Software` enum

- perf-event/CHANGELOG.md
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/). I haven't bothered adding entries for releases for versions before v0.5.0 since there wasn't a changelog originally.
> Add a changelog to perf-event2

- perf-event/CHANGELOG.md
- perf-event/examples/big-group.rs
- perf-event/examples/group.rs
- perf-event/src/events.rs
Code using `WhichCache` will continue to work, although it is `#[doc(hidden)]` and deprecated so it will get a warning.
> Rename `WhichCache` to `CacheId`

- perf-event/src/lib.rs
This is getting triggered by code within the `bitflags!` macro. There's nothing we can do about it so it is better to just silence it instead.
> Silence `clippy::assign_op_pattern` lint

- perf-event/CHANGELOG.md
- perf-event/Cargo.toml
- Expose the `perf_event_data` crate as the `data` module.
- Add `Record::parse_record` to parse records to `data::Record`.
- Add `Software::CGROUP_SWITCHES` and `Software::BPF_OUTPUT` events (#9). @Phantomical
- `Hardware` is no longer a rust enum. The constants remain the same.
- `Software` is no longer a rust enum. The constants remain the same.
- The same applies for `WhichCache`, `CacheOp`, and `CacheResult`.
- `WhichCache` has been renamed to `CacheId`.
> Prepare for v0.6.0 release

- perf-event/src/lib.rs
Always getting errors while developing is inconvenient. Better to leave it as a warning in dev mode while still keeping it as an error in release mode.
> Only warn on missing docs in debug, deny in release

- perf-event/CHANGELOG.md
- perf-event/examples/kprobe.rs
- perf-event/src/events/mod.rs
- perf-event/src/events/probe.rs
As it turns out, there is relatively little guidance on how to do this. However, these bindings are enough to expose the full kernel API.
> Add `KProbe` and `UProbe` events

- perf-event/CHANGELOG.md
- perf-event/Cargo.toml
- Expose the `IOC_SET_BPF` ioctl as `Counter::set_bpf`.
- Add `Event::update_attrs_with_data` to allow events to store references to
owned data within `Builder`'s `perf_event_attr` struct.
- Add `KProbe`, `UProbe`, and `Tracepoint` event types.
> Prepare for perf-event2 0.6.1 release

- perf-event/src/events/mod.rs
- perf-event/src/events/probe.rs
- perf-event/src/events/util.rs
This PR adds a internal helper type to do the part of reading `/sys/bus/event_source/devices/<pmu>/type`. Future event types added to this crate are likely to be dynamic PMUs so they will need this. Instead of having the same code copy-pasted everywhere it is better to get out ahead and just provide an easy-to-use type for this up front.
> Add a helper type for reading and caching dynamic PMU types 

- perf-event/rustfmt.toml
- perf-event/src/events/util.rs
- perf-event/src/flags.rs
- perf-event/src/lib.rs
It is not reasonable to expect people making PRs to manually do this. Better to have it enforced via rustfmt.
> Add rustfmt option to automatically group imports and reformat

- perf-event-open-sys/README.md
It should be pointing people to the perf-event2 crate instead of perf-event.
> Update the link to perf-event within the perf-event-open-sys2 readme

- perf-event/src/events/mod.rs
- perf-event/src/events/x86/msr.rs
This expands the documentation on the `Msr` and `MsrId` types to be much more comprehensive.
> Improve the documentation for the `x86::Msr` event.

- Cargo.toml
- perf-event/CHANGELOG.md
- perf-event/src/lib.rs
- perf-event/src/sampler.rs
The perf manpage documents how to do this. I have also tried to make the implementation generic enough that it should be possible to add support for other architectures easily enough.
> Add support for reading counters from userspace using rdpmc

- perf-event/CHANGELOG.md
- perf-event/src/sampler.rs
This seems to have been forgotten in the initial implementation. Having multiple instances of `Record` hanging around from the sample `Sampler` could potentially cause UB and will almost 1definitely permanently corrupt the ring buffer state. Unfortunately, the fix is a breaking change but it's better to do it now rather than have the issue remain.
> Make `Sampler::next` record take `&mut self` instead of `&self`

- perf-event/examples/println-cpi-raw.rs
- perf-event/src/events/mod.rs
- perf-event/src/events/raw.rs
Same as https://github.com/jimblandy/perf-event/pull/25
> Add support for Raw Events

- perf-event/CHANGELOG.md
- perf-event/src/sampler.rs
There was a reversed comparison when determining whether we should advance past the split within the buffer. It was checking whether `a.len() <= new_len` but it should have been checking whether `new_len <= a.len()`. This was leading to panics whenever a sampler record ended up being split.
I've fixed the if statement and added some test cases to cover both split cases with a truncate.
> Fix a panic within `ByteBuffer::truncate`

- perf-event/CHANGELOG.md
- perf-event/Cargo.toml
- Fixed a panic in `Sampler` when handling a record that wrapped around the end of the sampler ring buffer.
> Prepare for v0.7.2 release

- perf-event/Cargo.toml
- perf-event/src/events/cache.rs
Since `c_enum` v0.2 no longer supports declaring multiple enums in a single c_enum! block I have also gone and split up the blocks where applicable.
> Update the c_enum crate to v0.2

- perf-event/src/events/dynamic.rs
Turns out the correct `target_arch` condition here is `x86` instead of `i686`.
> Fix a conditional in the dynamic_msr_event test

- perf-event/src/group.rs
Hello there! I am a happy user of this library. I've got a small contribution to make.
I added a new method to `Group` that shortcuts creating an appropriate `Builder`.
If you aren't familiar with the `perf_event_open` API it will be frustrating to try figure out why this code blows up, reporting only `Error: Invalid argument (os error 22) `.
This method makes it easier and clearer to create groups with non-default settings.
```rust
use perf_event::events::Raw;
use perf_event::{Builder, Group};
fn main() -> anyhow::Result<()> {
let mut group = Group::new()?;
// The change I'm proposing:
// let mut group = Group::builder().one_cpu(0).build_group()?;
let port_usage = group.add(&Builder::new(Raw::new(0xA1 | (0x80 << 8))).one_cpu(0))?;
// …
```
> Add builder convenience method to Group

- perf-event-open-sys/Cargo.toml
- perf-event-open-sys/src/attr.rs
- perf-event-open-sys/src/lib.rs
This means that future changes made to the C perf_event_attr struct which replace existing fields with inline unions can continue to be non-breaking changes to the crate.
Furthermore, it is generally much more convenient to directly access the relevant fields instead of needing to go through the __bindgen_anon_x field first.
> Allow direct access to inline union fields on perf_event_attr

- perf-event/Cargo.toml
- perf-event/src/builder.rs
- perf-event/src/events/breakpoint.rs
- perf-event/src/events/dynamic.rs
- perf-event/src/events/probe.rs
- perf-event/src/events/raw.rs
Now that perf-event-open-sys2 supports directly accessing fields within inline unions in perf_event_attr we can take advantage of that to perform some cleanup on internal code in this crate.
> Access perf_event_attr fields directly instead of via anon fields

- perf-event-open-sys/src/bindings_aarch64.rs
- perf-event-open-sys/src/bindings_header.rs
- perf-event-open-sys/src/bindings_x86_64.rs
- perf-event-open-sys/src/functions.rs
- perf-event-open-sys/src/lib.rs
- perf-event/README.md
- perf-event/src/builder.rs
- perf-event/src/events/breakpoint.rs
- perf-event/src/events/cache.rs
- perf-event/src/events/hardware.rs
- perf-event/src/events/software.rs
- perf-event/src/flags.rs
- perf-event/src/lib.rs
- perf-event/src/sampler.rs
man7.org is great but hasn't been updated in a few years. Most manpages don't really change that often so this usually doesn't matter that much but the perf_event_open manpage changes fairly frequently. This means that the manpage at man7.org is missing a few options and will continue to get worse as time goes on.
mankier.com seems to be reliably updated to the most recent kernel version and has been going for about a decade now so it should be reliable enough to link to from the documentation.
> Update all manpage links to point to mankier.com

- perf-event/CHANGELOG.md
- perf-event/src/builder.rs
- perf-event/src/flags.rs
- perf-event/src/lib.rs
It turns out that there were a bunch of these that did not have corresponding builder methods. This PR should bring the crate up to full coverage.
> Add a bunch more builder method for `perf_event_attr` fields

- perf-event-open-sys/src/functions.rs
It is not necessary since we can generically cast to the right value by doing `ioctl as _`.
> Avoid unnecessary `#[cfg]` in `untyped_ioctl` function
